name: Node.js Deploy CI

on:
  push:
    branches:
      - source

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '17.x'
    - name: Build
      run: |
        npm install
        npm run build
    - name: Setup Git
      run: |
        git config --global user.name "bot"
        git config --global user.email "${{secrets.ACTIONS_EMAIL}}"
    - name: Deploy
      run: |
        git clone https://${{github.actor}}:${{github.token}}@github.com/${{github.repository}} -b main --depth 1 dist-branch
        mv dist-branch/.git dist/
        cd dist
        git add .
        git commit --allow-empty -m "built from ${{github.sha}}"
        git push --force-with-lease origin main
        
